[providers]
nodejs = "18"

[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = [
  "cd webapp && npm install"
]

[phases.build]
cmds = [
  "cd webapp && npm run build"
]

[start]
cmd = "cd webapp && npm start"
